include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore

  plugins:
    - custom_lint

linter:
  rules:
    invalid_annotation_target: false
    prefer_single_quotes: true
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
