name: git_search
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.1
  google_fonts: ^6.2.0
  url_launcher: ^6.2.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path_provider: ^2.1.2
  http: ^1.2.1
  collection: ^1.18.0
  flutter_hooks: ^0.20.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.11
  riverpod_lint: ^2.1.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.3
  go_router_builder: ^2.4.1
  build_verify: ^3.1.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  analyzer: ^5.13.0

flutter:
  generate: true

  uses-material-design: true
